### ISSUE TITLE
Player was nulled while joining

### ISSUE THREAD

**Issue by ASOwnerYT** [Papela/Nitrox-Cracked-Mod#78]
### Which version are you playing on?

1.8.0.0 (Latest release)

### Which OS are you playing on?

Linux

### On which platform did you buy Subnautica?

Other ;)

### Describe the issue.

When my friends try to join my server their game crash and I see error "Player was nulled while joining" in the server logs

### Relevant log output

[15:04:16.817] Providing session policies...
[15:04:17.792] Processing reservation request from ryan
[15:04:17.830] Reservation processed successfully: Username: ryan - [MultiplayerSessionReservation: PlayerId: 2, ReservationKey: 1bb91b6e-3c8e-4933-b106-ccad12a2aaeb, ReservationState: RESERVED, CorrelationId: c54a5c98-1cde-41a3-91ed-eb5976db3e01]
[15:04:21.429] Player was nulled while joining
[15:04:21.432] Server has paused, waiting for players to connect
[15:04:21.630] Player was nulled while joining
[15:04:21.630] Finished processing reservation. Remaining requests: 0
[15:04:21.698] World state saved
[15:04:21.698] Finished processing reservation. Remaining requests: 0
[15:05:05.202] Providing session policies...
[15:05:06.379] Processing reservation request from avince
[15:05:06.380] Reservation processed successfully: Username: avince - [MultiplayerSessionReservation: PlayerId: 3, ReservationKey: dc47dc54-9e62-4e32-bbe4-8e5b9d4a1163, ReservationState: RESERVED, CorrelationId: 55ba87e8-c7e6-437b-861e-e2c3e78b9a87]
[15:05:12.379] Player was nulled while joining
[15:05:12.379] Server has paused, waiting for players to connect
[15:05:12.517] World state saved
[15:05:12.517] Finished processing reservation. Remaining requests: 0

**Comment by Papela** [comment]
I've released version 1.8.0.1, try it and see if it fixes the error.

**Comment by shawarma123123** [comment]
> I've released version 1.8.0.1, try it and see if it fixes the error.

same thing happens on 1.8.0.1.

**Comment by augusto-junior7** [comment]
I'm having the same error

**Comment by MrSn0wy** [comment]
@Papela this happens because Nitrox has two more piracy checks. I managed to find them, they were very sneaky and made me feel very skizophrenic these last few days, haha

**Comment by Papela** [comment]
> @Papela this happens because Nitrox has two more piracy checks. I managed to find them, they were very sneaky and made me feel very skizophrenic these last few days, haha

I don't understand why it only happens to some people; I think it might be because of the "pirated" game they're using.
Anyway, if you've found any of the anti-piracy code that I've missed, you can make a pull request fixing it for everyone or tell me where it is. 😉

**Comment by MrSn0wy** [comment]
> > @Papela this happens because Nitrox has two more piracy checks. I managed to find them, they were very sneaky and made me feel very skizophrenic these last few days, haha
> 
> I don't understand why it only happens to some people; I think it might be because of the "pirated" game they're using.
> Anyway, if you've found any of the anti-piracy code that I've missed, you can make a pull request fixing it for everyone or tell me where it is. 😉

It is not the fault of the players, I've been testing with a real game and the moment I change the steamapi.dll it causes these fake bugs.

One of which is the applyPatch function, it seemingly exits with 0 once it hits that when being in the launch multiplayer logic, the thing that happens there is that a seperate library Nitrox.Analyzer in a different repo is being imported and injecting a piracy check into that function.

There is a third one that gets triggered while joining a game, giving more fake errors, I managed to patch it out, but I am unsure why it works, im guessing they are doing more code generation which makes the usage of the verified dll function not show up in my ide.

I will make a proper report in a bit once I find out where the third check is actually hidden. It also might be possible to not have to fork Nitrox.Analyzers in order to bypass it because of some fucked logic in their check lol

**Comment by Claonyx** [comment]
i dont wanna be annoying but can i get what im actually looking for and what i need to get rid of because im impatient :P (as in like the other piracy detections)

**Comment by Kirstukas** [comment]
Before finding out about this repository I was making a cracked version myself. I found it when trying to resolve this exact issue :D

Anyways, I resolved the issue by commenting out [this line](https://github.com/Papela/Nitrox-Cracked-Mod/blob/5ad2dd2396bf2398da8d3b30122f0caa62d2ea9c/NitroxPatcher/Patches/Dynamic/EscapePod_Start_Patch.cs#L100). I have no clue why it is there, as I don't really see any imminent reason for it in its vicinity.

My cracked copy works fine with Subnautica Jun-2025 82304 (tested with a buddy). If this fix is not enough, I am happy to share my changes :)

**Comment by Claonyx** [comment]
> Before finding out about this repository I was making a cracked version myself. I found it when trying to resolve this exact issue :D
> 
> Anyways, I resolved the issue by commenting out [this line](https://github.com/Papela/Nitrox-Cracked-Mod/blob/5ad2dd2396bf2398da8d3b30122f0caa62d2ea9c/NitroxPatcher/Patches/Dynamic/EscapePod_Start_Patch.cs#L100). I have no clue why it is there, as I don't really see any imminent reason for it in its vicinity.
> 
> My cracked copy works fine with Subnautica Jun-2025 82304 (tested with a buddy). If this fix is not enough, I am happy to share my changes :)

that patch also has the "69420" error code in hex im pretty sure 👍

**Comment by Bazylek47** [comment]
Got the same issue

**Comment by MrSn0wy** [comment]
> Before finding out about this repository I was making a cracked version myself. I found it when trying to resolve this exact issue :D
> 
> Anyways, I resolved the issue by commenting out [this line](https://github.com/Papela/Nitrox-Cracked-Mod/blob/5ad2dd2396bf2398da8d3b30122f0caa62d2ea9c/NitroxPatcher/Patches/Dynamic/EscapePod_Start_Patch.cs#L100). I have no clue why it is there, as I don't really see any imminent reason for it in its vicinity.
> 
> My cracked copy works fine with Subnautica Jun-2025 82304 (tested with a buddy). If this fix is not enough, I am happy to share my changes :)

YES! this is the key, the callHook bytes in the top of the file resolve to `Nitrox.Model.Platforms.OS.Shared.FileSystemInstanceIsTrustedFile`. Now I finally understand why setting that function to always return true worked.

For a patch to that piracy check I would recommend hard-coding https://github.com/Papela/Nitrox-Cracked-Mod/blob/5ad2dd2396bf2398da8d3b30122f0caa62d2ea9c/NitroxModel/Platforms/OS/Windows/Internal/Win32Native.cs#L101C9-L101C10 to `true`.

For the second piracy check I mentioned, its hidden in https://github.com/SubnauticaNitrox/Nitrox.Analyzers/blob/79ad2e25ec9cdf45ae69a0f3362ce6448a8b65c6/src/Nitrox.Analyzers/Generators/GuardGenerator.cs#L131
However there is a way to fix it without forking Nitrox.Analyzers. 
Here is where the function gets called: https://github.com/Papela/Nitrox-Cracked-Mod/blob/5ad2dd2396bf2398da8d3b30122f0caa62d2ea9c/Nitrox.Launcher/ViewModels/LaunchGameViewModel.cs#L151
if you were to change the signature of that function to `NitroxEntryPatch.Apply("", NitroxUser.GamePath);` it would work, since the piracy check only checks the first paramater, and if its empty, it trusts it.

Then in the actual function you could just do 
```C#
    public static async Task Apply(string subnauticaBasePath, string second_argument)
    {
        subnauticaBasePath = second_argument;
```

These are all the piracy checks i've found. Have been playing it with a friend fine now.

**Comment by Papela** [comment]
> > Before finding out about this repository I was making a cracked version myself. I found it when trying to resolve this exact issue :D
> > Anyways, I resolved the issue by commenting out [this line](https://github.com/Papela/Nitrox-Cracked-Mod/blob/5ad2dd2396bf2398da8d3b30122f0caa62d2ea9c/NitroxPatcher/Patches/Dynamic/EscapePod_Start_Patch.cs#L100). I have no clue why it is there, as I don't really see any imminent reason for it in its vicinity.
> > My cracked copy works fine with Subnautica Jun-2025 82304 (tested with a buddy). If this fix is not enough, I am happy to share my changes :)
> 
> YES! this is the key, the callHook bytes in the top of the file resolve to `Nitrox.Model.Platforms.OS.Shared.FileSystemInstanceIsTrustedFile`. Now I finally understand why setting that function to always return true worked.
> 
> For a patch to that piracy check I would recommend hard-coding https://github.com/Papela/Nitrox-Cracked-Mod/blob/5ad2dd2396bf2398da8d3b30122f0caa62d2ea9c/NitroxModel/Platforms/OS/Windows/Internal/Win32Native.cs#L101C9-L101C10 to `true`.
> 
> For the second piracy check I mentioned, its hidden in https://github.com/SubnauticaNitrox/Nitrox.Analyzers/blob/79ad2e25ec9cdf45ae69a0f3362ce6448a8b65c6/src/Nitrox.Analyzers/Generators/GuardGenerator.cs#L131 However there is a way to fix it without forking Nitrox.Analyzers. Here is where the function gets called:
> 
> [Nitrox-Cracked-Mod/Nitrox.Launcher/ViewModels/LaunchGameViewModel.cs](https://github.com/Papela/Nitrox-Cracked-Mod/blob/5ad2dd2396bf2398da8d3b30122f0caa62d2ea9c/Nitrox.Launcher/ViewModels/LaunchGameViewModel.cs#L151)
> 
> Line 151 in [5ad2dd2](/Papela/Nitrox-Cracked-Mod/commit/5ad2dd2396bf2398da8d3b30122f0caa62d2ea9c)
>  await NitroxEntryPatch.Apply(NitroxUser.GamePath); 
> 
> if you were to change the signature of that function to `NitroxEntryPatch.Apply("", NitroxUser.GamePath);` it would work, since the piracy check only checks the first paramater, and if its empty, it trusts it.
> 
> Then in the actual function you could just do
> 
>     public static async Task Apply(string subnauticaBasePath, string second_argument)
>     {
>         subnauticaBasePath = second_argument;
> 
> These are all the piracy checks i've found. Have been playing it with a friend fine now.

Wow, amazing work! 💪
As soon as I have some time, I'll try to release an update with your solution, thank you so much, really.
Would it be possible for you to create a PR?
Obviously, if you want, give yourself credit in the Launcher for helping so much.

**Comment by Kirstukas** [comment]
> > Before finding out about this repository I was making a cracked version myself. I found it when trying to resolve this exact issue :D
> > Anyways, I resolved the issue by commenting out [this line](https://github.com/Papela/Nitrox-Cracked-Mod/blob/5ad2dd2396bf2398da8d3b30122f0caa62d2ea9c/NitroxPatcher/Patches/Dynamic/EscapePod_Start_Patch.cs#L100). I have no clue why it is there, as I don't really see any imminent reason for it in its vicinity.
> > My cracked copy works fine with Subnautica Jun-2025 82304 (tested with a buddy). If this fix is not enough, I am happy to share my changes :)
> 
> YES! this is the key, the callHook bytes in the top of the file resolve to `Nitrox.Model.Platforms.OS.Shared.FileSystemInstanceIsTrustedFile`. Now I finally understand why setting that function to always return true worked.
> 
> For a patch to that piracy check I would recommend hard-coding https://github.com/Papela/Nitrox-Cracked-Mod/blob/5ad2dd2396bf2398da8d3b30122f0caa62d2ea9c/NitroxModel/Platforms/OS/Windows/Internal/Win32Native.cs#L101C9-L101C10 to `true`.
> 
> For the second piracy check I mentioned, its hidden in https://github.com/SubnauticaNitrox/Nitrox.Analyzers/blob/79ad2e25ec9cdf45ae69a0f3362ce6448a8b65c6/src/Nitrox.Analyzers/Generators/GuardGenerator.cs#L131 However there is a way to fix it without forking Nitrox.Analyzers. Here is where the function gets called:
> 
> [Nitrox-Cracked-Mod/Nitrox.Launcher/ViewModels/LaunchGameViewModel.cs](https://github.com/Papela/Nitrox-Cracked-Mod/blob/5ad2dd2396bf2398da8d3b30122f0caa62d2ea9c/Nitrox.Launcher/ViewModels/LaunchGameViewModel.cs#L151)
> 
> Line 151 in [5ad2dd2](/Papela/Nitrox-Cracked-Mod/commit/5ad2dd2396bf2398da8d3b30122f0caa62d2ea9c)
>  await NitroxEntryPatch.Apply(NitroxUser.GamePath); 
> 
> if you were to change the signature of that function to `NitroxEntryPatch.Apply("", NitroxUser.GamePath);` it would work, since the piracy check only checks the first paramater, and if its empty, it trusts it.
> 
> Then in the actual function you could just do
> 
>     public static async Task Apply(string subnauticaBasePath, string second_argument)
>     {
>         subnauticaBasePath = second_argument;
> 
> These are all the piracy checks i've found. Have been playing it with a friend fine now.

IIRC the generator only guards the launcher, yet the game starts?

If you try starting multiplayer version thru the official Nitrox launcher, it will close without doing anything (Because the wrapper guarding `Apply`, calls `Environment.Exit`). Yet in this version it seems not to be the case.

I ran debug and release builds for [1.8.0.0](5ad2dd2396bf2398da8d3b30122f0caa62d2ea9c) (main) and [1.8.0.1](https://github.com/Papela/Nitrox-Cracked-Mod/tree/cd7e29c49252e7f9da0c18570fceb9fedc9f61c1), they both started the game but failed to join a server.

Then by removing `yield return new CodeInstruction(OpCodes.Call, Reflect.Method(() => Application.Quit(default)));` I was able to join a server on both 1.8.0.0, 1.8.0.1 (did not play extensively thou).

What I mean is that I suspect @Papela has already patched out that guardian generator, because I did not trip it during testing (nor OP seems to have). And all that is needed, is as you suggested set `IsTrusted` to always return true. :)

**Comment by MrSn0wy** [comment]
@Kirstukas did you test this on the linux or the macos launcher? I'm pretty sure that it doesnt do the guardian check there since it checks if its windows only, but maybe since the game runs trough proton, aka "windows" the piracy checks do trigger in-game. I use linux but never touched the linux version of the launcher, just ran it all trough wine and in a vm.

**Comment by MrSn0wy** [comment]
> 
> Wow, amazing work! 💪
> As soon as I have some time, I'll try to release an update with your solution, thank you so much, really.
> Would it be possible for you to create a PR?
> Obviously, if you want, give yourself credit in the Launcher for helping so much.

I could make a PR yeah, will try to make one in a few hours, thanks for the appreciation.

**Comment by Kirstukas** [comment]
> [@Kirstukas](https://github.com/Kirstukas) did you test this on the linux or the macos launcher? I'm pretty sure that it doesnt do the guardian check there since it checks if its windows only, but maybe since the game runs trough proton, aka "windows" the piracy checks do trigger in-game. I use linux but never touched the linux version of the launcher, just ran it all trough wine and in a vm.

I am a windows user, I checked nuget cache to ensure that both projects use the same "Nitrox.Analyzers" version, I am quite sure the launcher is muffling the check somehow. But I think it matters not.

Your fix seems reasonable, I can't really judge it due to my severe lack of knowledge in C#/dotnet/whatever.

**Comment by Marshpill0w** [comment]
Hello, i dont know if you guys found the solution and made it to work but im struggling to find the issue whether i have the wrong version of subnautica or my firewall being a d**k i dont really know xD.
I'm asking to find a solution for this obviously as i have the "v08122025" cracked version and its from "https://koyso.to/game/317" i hope you can reply to me so i just know and thank you all for your effort its amazing how everyone in contributing into this to make use the players have a amazing experience heh

**Comment by Kirstukas** [comment]
They seem to be working on the fix [here](https://github.com/Papela/Nitrox-Cracked-Mod/pull/88).

**Comment by Papela** [comment]
If anyone is experiencing this bug, could you try [this version](https://github.com/Papela/Nitrox-Cracked-Mod/pull/94#issuecomment-3671483727) and let us know if it fixes it?

**Comment by exploshet** [comment]
> If anyone is experiencing this bug, could you try [this version](https://github.com/Papela/Nitrox-Cracked-Mod/pull/94#issuecomment-3671483727) and let us know if it fixes it?

it still doesnt work for me

**Comment by Papela** [comment]
> > If anyone is experiencing this bug, could you try [this version](https://github.com/Papela/Nitrox-Cracked-Mod/pull/94#issuecomment-3671483727) and let us know if it fixes it?
> 
> it still doesnt work for me

Are you sure you're using the same version and that the error is the same?
Some people are saying they had the bug before, but that it's fixed with this build.

**Comment by exploshet** [comment]
> > > If anyone is experiencing this bug, could you try [this version](https://github.com/Papela/Nitrox-Cracked-Mod/pull/94#issuecomment-3671483727) and let us know if it fixes it?
> > 
> > 
> > it still doesnt work for me
> 
> Are you sure you're using the same version and that the error is the same? Some people are saying they had the bug before, but that it's fixed with this build.

nvm it loads into the game now but im getting another error where it crashes like 5 seconds after loading in

<img width="1025" height="261" alt="Image" src="https://github.com/user-attachments/assets/d71b9db4-9b48-47c0-a224-cddb00488158" />

is there a discord where i can get assistance from? the discord button on nitrox app doesnt work for me

edit- i fixed the issue, turning off windows security fixed it for me

**Comment by Papela** [comment]
> > > > If anyone is experiencing this bug, could you try [this version](https://github.com/Papela/Nitrox-Cracked-Mod/pull/94#issuecomment-3671483727) and let us know if it fixes it?
> > > 
> > > 
> > > it still doesnt work for me
> > 
> > Are you sure you're using the same version and that the error is the same? Some people are saying they had the bug before, but that it's fixed with this build.
> 
> nvm it loads into the game now but im getting another error where it crashes like 5 seconds after loading in
> 
> <img width="1025" height="261" alt="Image" src="https://github.com/user-attachments/assets/d71b9db4-9b48-47c0-a224-cddb00488158" />
> 
> is there a discord where i can get assistance from? the discord button on nitrox app doesnt work for me
> 
> edit- i fixed the issue, turning off windows security fixed it for me

The problem seems to have been something else, but it's interesting to know how you fixed it. Thanks 🫶

**Comment by exploshet** [comment]
> > > > > If anyone is experiencing this bug, could you try [this version](https://github.com/Papela/Nitrox-Cracked-Mod/pull/94#issuecomment-3671483727) and let us know if it fixes it?
> > > > 
> > > > 
> > > > it still doesnt work for me
> > > 
> > > 
> > > Are you sure you're using the same version and that the error is the same? Some people are saying they had the bug before, but that it's fixed with this build.
> > 
> > 
> > nvm it loads into the game now but im getting another error where it crashes like 5 seconds after loading in
> > <img alt="Image" width="1025" height="261" src="https://private-user-images.githubusercontent.com/210521853/529347798-d71b9db4-9b48-47c0-a224-cddb00488158.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjY0ODkzMzcsIm5iZiI6MTc2NjQ4OTAzNywicGF0aCI6Ii8yMTA1MjE4NTMvNTI5MzQ3Nzk4LWQ3MWI5ZGI0LTliNDgtNDdjMC1hMjI0LWNkZGIwMDQ4ODE1OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTIyM1QxMTIzNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNTk4N2I1NmEwMzA4YTljZWRiZTI0ZDcxMmU4MjIyOThlNWY0YTQ5MzAxNDZjMDc3NjFjY2Y1YzRmZThiYWEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gDrhKF63wdpC8PztyoG2C3ExZz7xsVRTfRAmXw4hxh8">
> > is there a discord where i can get assistance from? the discord button on nitrox app doesnt work for me
> > edit- i fixed the issue, turning off windows security fixed it for me
> 
> The problem seems to have been something else, but it's interesting to know how you fixed it. Thanks 🫶

nevermind it still doesnt work, it works for like one second and then crashes pls help

**Comment by ShxrkX13** [comment]
How do i fix this issue??

**Comment by Papela** [comment]
Thanks to PR #94, the issue will be fixed in the next version, which I will try to release this weekend, including the changes from 1.8.1.0

**Comment by Papela** [comment]
Fixed in version: **[1.8.1.0](https://github.com/Papela/Nitrox-Cracked-Mod/releases/tag/V1.8.1.0)**
